version: "3.0"
services:
    webhook-server:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        environment:
            MODULE_NAME: "webhook-server"
            MODULE_TYPE: "Input"
            EGRESS_URLS: "https://sanyamarya.free.beeceptor.com"
            HOST_PORT: 80
            LOG_LEVEL: "debug"
        ports:
            - 8080:80
